### PR TITLE
Add 'await' on call to pr merge and branch delete

### PR DESCRIPTION
**Pull request by aaron-trout**
I am no Javascript developer, but I think there should be some `await` here :D

So the bot was failing to merge my PR, it would just delete the branch and close the PR. Now I added these awaits and used my fork, I get a build fail on the merge step saying this:

```
##[error]You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
```

I'm not sure exactly why it is failing / being blocked, but that is a separate problem! At least we wait for the call to merge to return successfully before going ahead and deleting the branch now!

### CODE REVIEW

**Comment by aaron-trout** [comment]
Thanks @mbellgb for helping to spot this 👍

**Comment by squalrus** [comment]
Thank you for this @aaron-trout and @mbellgb! I will look into this ASAP.

**Comment by squalrus** [comment]
Actually, yeah, this makes sense. I am going to integrate and test.

**Comment by squalrus** [comment]
> I'm not sure exactly why it is failing / being blocked, but that is a separate problem!

Yes, I believe there is an issue with forked contributions.

**Comment by squalrus** [comment]
@aaron-trout If we integrate this, would you mind opening another PR from your fork so we can debug the fork workflow?

**Comment by aaron-trout** [comment]
> @aaron-trout If we integrate this, would you mind opening another PR from your fork so we can debug the fork workflow?

@squalrus sure thing! It looks like a similar problem to what I'm getting on our private repo actually 😅 

```
##[error]You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
```

I tried to swtich to using a Github App integration and doing some plumbing to give the merge bot a token for the app, but then I got this error:

```
##[error]Resource not accessible by integration
```

**Comment by aaron-trout** [comment]
Managed to get the permissions error fixed! I had only granted access to pull requests for the app / integration, needed to add read access to checks as well.

**Pull request merged**
