### PR TITLE
Optionally delete source branch

### PR DESCRIPTION
**Pull request by aaron-trout**
This is useful if you have "Automatically delete head branches" enabled on your repo:

Screenshot 2020-09-03 at 13 45 52

### CODE REVIEW

**Review by bartelemi — APPROVED** [review]
LGTM :+1:

**Review by squalrus — APPROVED** [review]
Awesome! Thank you so much for the contribution(s) and apologies for the delay.

**Comment by squalrus** [comment]
Just pushed an update adjusting the tests based on these changes.

**Comment by aaron-trout** [comment]
> Just pushed an update adjusting the tests based on these changes.

@squalrus looks good to me!

**Comment by squalrus** [comment]
Manually integrating to work around #40, see #41.

**Pull request merged**
